### ISSUE TITLE
bundler: failed to load command: bundler-integrity, RubyGems API response (RuntimeError)

### ISSUE THREAD

**Issue by benoittgt** [diffend-io/bundler-integrity#1]
Hello @mensfeld 

First thank you very much for the hard work on this. I just notice an issue when the gem is hosted in private repo like [Fury]( https://fury.co/l/gem-server).

```ruby
# Gemfile
source 'https://<MaciejRocks>@gem.fury.io/<company-name>/' do
  gem 'super-gem'
end
```

```sh
bundler: failed to load command: bundler-integrity (/Users/benoit/.rbenv/versions/3.1.2/bin/bundler-integrity)
/Users/benoit/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-integrity-1.0.7/bin/bundler-integrity:54:in `block in <top (required)>':super-gem-4.4.1.gem not found in the RubyGems API response (RuntimeError)
	from /Users/benoit/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.11/lib/bundler/spec_set.rb:136:in `each'
	from /Users/benoit/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.11/lib/bundler/spec_set.rb:136:in `each'
	from /Users/benoit/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-integrity-1.0.7/bin/bundler-integrity:30:in `<top (required)>'
	from /Users/benoit/.rbenv/versions/3.1.2/bin/bundler-integrity:25:in `load'
	from /Users/benoit/.rbenv/versions/3.1.2/bin/bundler-integrity:25:in `<top (required)>'
	from /Users/benoit/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.11/lib/bundler/cli/exec.rb:58:in `load'
	from /Users/benoit/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.11/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/benoit/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.11/lib/bundler/cli/exec.rb:23:in `run'
	from /Users/benoit/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.11/lib/bundler/cli.rb:483:in `exec'
	from /Users/benoit/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.11/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/benoit/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.11/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/benoit/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.11/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/benoit/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.11/lib/bundler/cli.rb:31:in `dispatch'
	from /Users/benoit/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.11/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/benoit/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.11/lib/bundler/cli.rb:25:in `start'
	from /Users/benoit/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.11/exe/bundle:48:in `block in <top (required)>'
	from /Users/benoit/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.11/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	from /Users/benoit/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.11/exe/bundle:36:in `<top (required)>'
	from /Users/benoit/.rbenv/versions/3.1.2/bin/bundle:25:in `load'
	from /Users/benoit/.rbenv/versions/3.1.2/bin/bundle:25:in `<main>'
```

🌮

**Comment by mensfeld** [comment]
Can you check 1.0.9?

**Comment by benoittgt** [comment]
Working great with bundler-integrity 1.0.9. Thanks for the quick fix.

**Comment by mPanasiewicz** [comment]
Version `1.0.9` works ;-)
